# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Quick Script Bash'

- task: Bash@3
  displayName: 'Static Code Check'
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Static Code Check'
- task: Docker@2
  displayName: 'Build UI'
  inputs:
    containerRegistry: 'mjtest'
    repository: 'yelb-ui'
    command: 'buildAndPush'
    Dockerfile: '**/yelb-ui/Dockerfile'

- task: Docker@2
  displayName: 'Build AppServer'
  inputs:
    containerRegistry: 'mjtest'
    repository: 'yelb-appserver'
    command: 'buildAndPush'
    Dockerfile: '**/yelb-appserver/Dockerfile'

- task: Docker@2
  displayName: 'Build DB'
  inputs:
    containerRegistry: 'mjtest'
    repository: 'yelb-db'
    command: 'buildAndPush'
    Dockerfile: '**/yelb-db/Dockerfile'
